### PR TITLE
2

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit 58fc716 has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit 58fc716 with merge 65cf49c...

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit 9035a6b has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit 9035a6b with merge 942bbf3...

**Comment by badboy** [comment]
@not-a-robot retry

**Comment by ghost** [comment]
:hourglass: Testing commit 9035a6b with merge 4228af8...

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit 7a097da has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit 7a097da with merge 13a227a...

**Comment by badboy** [comment]
@not-a-robot retry

**Comment by ghost** [comment]
:zap: Test exempted - [status](https://travis-ci.org/badboy/homu-test-project/builds/124561876)

**Pull request merged**
